import RealModule

#if canImport(_Differentiation)
import _Differentiation
#endif

// Elementary functions are generated for the SIMD protocol and thus every concrete SIMD type can conform to `ElementaryFunctions`
// Actual implementation is generated by the CodeGeneratorPlugin
// Add actual conformances to `ElementaryFunctions` to individual SIMD types
extension SIMD2: @retroactive ElementaryFunctions where Scalar: FloatingPoint & ElementaryFunctions {}
extension SIMD3: @retroactive ElementaryFunctions where Scalar: FloatingPoint & ElementaryFunctions {}
extension SIMD4: @retroactive ElementaryFunctions where Scalar: FloatingPoint & ElementaryFunctions {}
extension SIMD8: @retroactive ElementaryFunctions where Scalar: FloatingPoint & ElementaryFunctions {}
extension SIMD16: @retroactive ElementaryFunctions where Scalar: FloatingPoint & ElementaryFunctions {}
extension SIMD32: @retroactive ElementaryFunctions where Scalar: FloatingPoint & ElementaryFunctions {}
extension SIMD64: @retroactive ElementaryFunctions where Scalar: FloatingPoint & ElementaryFunctions {}
