name: Pull Request

on: [pull_request]

jobs:
  Lint:
    runs-on: macos-26
    steps:
      - uses: actions/checkout@v4
      - name: SwiftFormat
        run: swiftformat --lint --strict . --reporter github-actions-log
  test-ubuntu-latest:
    name: Test Swift ${{ matrix.swift }} Ubuntu Latest
    strategy:
      matrix:
        swift: ["6.2", "6.3"]
    runs-on: ubuntu-latest
    container: swift:${{ matrix.swift }}
    steps:
      - uses: actions/checkout@v4
      - name: Run Tests
        run: swift test -Xswiftc -warnings-as-errors

  test-macos-26:
    name: Test Swift macos-26
    runs-on: macos-26
    steps:
      - uses: actions/checkout@v4
      - name: Run Tests
        run: |
          swift test -Xswiftc -warnings-as-errors

  test-wasm:
    name: WASM compilation check
    uses: swiftlang/github-workflows/.github/workflows/swift_package_test.yml@0.0.11
    with:
      enable_linux_checks: false
      enable_windows_checks: false
      enable_wasm_sdk_build: true
      wasm_sdk_versions: "[\"6.3\"]"
